### ISSUE TITLE
Validation of the sense of coherence (SOC) scale in a French population

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#444]
https://osf.io/pj5mr/

**Comment by ben-domingue** [comment]
https://www.i-jmr.org/2024/1/e50284

**Comment by ben-domingue** [comment]
9-25-2024 from paul sebo <paulsebo@hotmail.com>

**Comment by KingArthur0205** [comment]
Data:
[VSOCFP_Sebo_2024.csv](https://github.com/user-attachments/files/17637479/VSOCFP_Sebo_2024.csv)

Code:
```
# Paper：https://www.i-jmr.org/2024/1/e50284
# Data:https://osf.io/pj5mr/ 

library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)
library(readr)
library(readxl)
library(sas7bdat)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id"))])) == (ncol(df) - 1)), ]
  return(df)
}

data_df <- read_dta("SOC_osf.dta")
data_df <- data_df %>%
  mutate(id = row_number())

data_df[] <- lapply(data_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

SOC_df <- data_df |>
  select(starts_with("SOC"),-ends_with("R"),-ends_with("C"),-ends_with("MA"),-ends_with("Me"),-ends_with("tot"), id)
SOC_df <- remove_na(SOC_df)
SOC_df <- pivot_longer(SOC_df, cols=-c(id), names_to="item", values_to="resp")

save(SOC_df, file="VSOCFP_Sebo_2024.Rdata")
write.csv(SOC_df, "VSOCFP_Sebo_2024.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
**SOC_df**: 13 items, 804 participants, ranging from 1 to 7.

**Comment by KingArthur0205** [comment]
@ben-domingue Could you help fill in the license info for this dataset at row 630 of the dictionary please? Thank you!

**Comment by ben-domingue** [comment]
one question about this one before i ship it. i'm seeing 9 items but if you look at the abstract i'd have expected 13 or 8. just wanted to see what was up. 
https://www.i-jmr.org/2024/1/e50284

and license info added

**Comment by ben-domingue** [comment]
@KingArthur0205 see above.

**Comment by KingArthur0205** [comment]
@ben-domingue Sorry I meant to highlight the mismatch, but my 1st draft wasn't saved and I completely forgot while writing this 2nd version of notes.

They thought there were only 8 items that were truly valuable to be included from the developed questionnaire SOC-8. 
The **extra item 5** seemed to also be included because it was one of the items whose "Loevinger H coefficients were <0.30 for 9 of the 13 items."

"The psychometric properties of the 3-dimension SOC-13 were poor, unlike the unidimensional SOC-8. A questionnaire built only with these 8 items could be a good candidate to measure the SOC. However, further validation studies are needed before recommending its use in research."

**Comment by KingArthur0205** [comment]
@ben-domingue In this case, shall we only keep the 8 items in the POC-8 scale and throw away that extra one?

**Comment by ben-domingue** [comment]
@KingArthur0205 yeah maybe let's go with 8. i don't necessarily have a problem with the 9 but more straightfwd to just use their 8 in this case.

**Comment by KingArthur0205** [comment]
Certainly! I'll make the changes right now

**Comment by KingArthur0205** [comment]
@ben-domingue Data, code, and PR aer all updated accordingly. : )
