### ISSUE TITLE
Can destigmatizing mental health increase willingness to seek help? Experimental evidence from Nepal

### ISSUE THREAD

**Issue by joshgilbert1994** [ben-domingue/irw#580]
Beautiful RCT out today in JPAM with item level outcomes but no license.

Article: https://onlinelibrary.wiley.com/doi/epdf/10.1002/pam.22643
Data: https://www.dropbox.com/scl/fo/jp41djskes00ssrbzm4ez/ABgU29_SZ3L4jpeNRIFVpHo?rlkey=tj7ojr4spweeupyyiidisi103&e=1&dl=0

**Comment by ben-domingue** [comment]
email approval 10-14-2024

**Comment by KingArthur0205** [comment]
The paper mentioned that participants took a series of questionnaires(e.g., PHQ-8, GAD7, etc.). However, no item-level data is given for these questionnaires.

The repo contains 2 datasets, one for parents and one for children

**Parent:**
The original dataset included 2,533 household participants. The author removed 48 households due to incorrect phone numbers, treatment group discrepancies, enumerator gender mismatches, and vignette inconsistencies, resulting in a final sample of **2,485 households**, consistent with the numbers reported in the paper. Our processed dataset includes 24 items with numeric responses on a mixed scale, comprising both binary (0/1) and 5-point Likert scale items.

**Children:**
Similarly, the original dataset contained 2362 participants. After removal of those without consent and provided wrong info, the processed dataset has **2348 participants**. Our processed dataset includes 13 items with numeric responses on a mixed scale, comprising both binary (0/1) and 5-point Likert scale items.

**Comment by KingArthur0205** [comment]
Data:
[EEN_Lacey_2024.zip](https://github.com/user-attachments/files/17540963/EEN_Lacey_2024.zip)

Code:
```
# Paper: https://onlinelibrary.wiley.com/doi/epdf/10.1002/pam.22643
# Data: https://www.dropbox.com/scl/fo/jp41djskes00ssrbzm4ez/ABgU29_SZ3L4jpeNRIFVpHo?rlkey=tj7ojr4spweeupyyiidisi103&e=1&dl=0
library(haven)
library(dplyr)
library(tidyr)

ad_df <- read_dta("adolescent_cleaned.dta")
parent_df <- read_dta("parent_cleaned.dta")

# ------ Data Pre-process for Parent Data------
# Remove households that didn't give consents.
parent_df <- parent_df[parent_df$consent_disagree != 1, ]
# Remove households that didn't give correct info
parent_df <- parent_df[parent_df$multi_phone != 1, ]
parent_df <- parent_df[parent_df$wrong_vig != 1, ]
parent_df <- parent_df[parent_df$wrong_treatment != 1, ]
parent_df <- parent_df[parent_df$wrong_enum_gender != 1, ]

# ------ Process Parent Data ------
parent_df <- parent_df |>
  rename(id=HHID, treat=treatment) |>
  select(-starts_with("consent"), -starts_with("wrong"), -counsellor_willingnesstopay, -mh_child_time) |>
  select(id, treat, ends_with("major"), starts_with("mh"), starts_with("not"), starts_with("vig"), starts_with("covid"),
         starts_with("counsel"), starts_with("less"))

parent_df[] <- lapply(parent_df, function(x) as.numeric(as.character(x))) # Remove attributes
parent_df[parent_df == -98] <- NA
parent_df <- pivot_longer(parent_df, cols=-c(id, treat), names_to="item", values_to="resp")

save(parent_df, file="EEN_Lacey_2024_Parent.Rdata")
write.csv(parent_df, "EEN_Lacey_2024_Parent.csv", row.names=FALSE)

# ------ Data Pre-process for Children Data------
# Remove households that didn't give consents.
ad_df <- ad_df[ad_df$consent != 0, ]
# Remove households that didn't give correct info
ad_df <- ad_df[ad_df$multi_phone != 1, ]
ad_df <- ad_df[ad_df$wrong_vig != 1, ]
ad_df <- ad_df[ad_df$wrong_treatment != 1, ]
ad_df <- ad_df[ad_df$wrong_enum_gender != 1, ]

# ------ Process Children Data ------
ad_df <- ad_df |>
  rename(id=HHID, treat=combine_treat) |>
  select(id, treat, ends_with("major"), starts_with("man"), starts_with("counsel"),
         group_samesex, Howcomfortabledidyoufeel, helpline_willcall)
ad_df[] <- lapply(ad_df, function(x) as.numeric(as.character(x))) # Remove attributes
ad_df[ad_df == -98] <- NA
ad_df <- pivot_longer(ad_df, cols=-c(id, treat), names_to="item", values_to="resp")

save(ad_df, file="EEN_Lacey_2024_Children.Rdata")
write.csv(ad_df, "EEN_Lacey_2024_Children.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
@ben-domingue 2 data entries added into dictionary at row 608 and 609. No PR yet for this one

**Comment by ben-domingue** [comment]
@KingArthur0205 ship PR
also note that the derived license for these will not be email approval. typically my request is that i repost with a specific license and it is that license that we put in that column :)

**Comment by KingArthur0205** [comment]
@ben-domingue Got it. I actually meant to use those as placeholders since I don’t yet have the derived license information.. : (

**Comment by ben-domingue** [comment]
totally. i will have that inthe email so maybe just tag that or something.
